### ISSUE TITLE
优化建议：鼠标滑动卡顿

### ISSUE THREAD

**Issue by core-admin** [lengyibai/wzry#21]
自定义了鼠标效果，但感觉非常卡顿，延迟非常高，给人造成卡顿的效果，作者不知道这块能不能优化优化

**Comment by lengyibai** [comment]
我19年4000块的电脑都能保持在75帧左右，你检查一下是不是浏览器没有开启GPU硬件加速

**Comment by core-admin** [comment]
> 我19年4000块的电脑都能保持在75帧左右，你检查一下是不是浏览器没有开启GPU硬件加速，或者在你的任务管理器-性能的地方看看在鼠标移动的时候，GPU占用率高不高

看了下性能面板，长任务的占比非常大
<img width="1615" alt="image" src="https://github.com/user-attachments/assets/c6bd7f22-2c62-47db-b552-918cccc672e5">
